const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Sin,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Behaviors.Fade,
		C3.Plugins.Audio,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch,
		C3.Plugins.video,
		C3.Plugins.HTMLElement,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Text.Acts.TypewriterFinish,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Text.Acts.SetPos,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Text.Cnds.OnTypewriterTextFinished,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.video.Acts.Pause,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.video.Acts.SetLooping,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetOpacity
	];
};
self.C3_JsPropNameTable = [
	{移動到: 0},
	{b1: 0},
	{b2: 0},
	{b3: 0},
	{b4: 0},
	{b5: 0},
	{s1: 0},
	{s2: 0},
	{s3: 0},
	{s4: 0},
	{s5: 0},
	{大: 0},
	{正弦: 0},
	{大鼓: 0},
	{拖放: 0},
	{大鼓2: 0},
	{"大＆小": 0},
	{小: 0},
	{小鼓: 0},
	{小鼓2: 0},
	{title: 0},
	{start: 0},
	{home: 0},
	{starttext: 0},
	{滑鼠: 0},
	{"1map": 0},
	{"2mapp": 0},
	{"3map": 0},
	{Text: 0},
	{Text2: 0},
	{Text3: 0},
	{淡入淡出: 0},
	{"1text": 0},
	{"1Understand": 0},
	{narration: 0},
	{oldSchool: 0},
	{trap: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Spectrum: 0},
	{boom: 0},
	{bap: 0},
	{map: 0},
	{oldtrap: 0},
	{next: 0},
	{help: 0},
	{play: 0},
	{ok: 0},
	{ill: 0},
	{音頻: 0},
	{子彈: 0},
	{SensorDetector: 0},
	{Sprite4: 0},
	{ChallengeSuccessOrFailure: 0},
	{again: 0},
	{clear: 0},
	{back: 0},
	{trapbg: 0},
	{dialogBox: 0},
	{PedalPull1: 0},
	{bass: 0},
	{Spectrum2: 0},
	{Spectrum3: 0},
	{PedalPull2: 0},
	{bass2: 0},
	{box: 0},
	{box2: 0},
	{box3: 0},
	{box4: 0},
	{box5: 0},
	{box6: 0},
	{box7: 0},
	{box8: 0},
	{h1: 0},
	{h2: 0},
	{h3: 0},
	{h4: 0},
	{l1: 0},
	{l2: 0},
	{l3: 0},
	{l4: 0},
	{averagecard: 0},
	{shortLongcard: 0},
	{tripletscard: 0},
	{Text4: 0},
	{wordCardBelow: 0},
	{Text5: 0},
	{CharacterCardDescription: 0},
	{backclick: 0},
	{Sprite5: 0},
	{QuizAndCreate: 0},
	{Sprite6: 0},
	{click: 0},
	{clicking: 0},
	{cube: 0},
	{cube2: 0},
	{cube3: 0},
	{cube4: 0},
	{cube5: 0},
	{cube6: 0},
	{cube7: 0},
	{cube8: 0},
	{average1: 0},
	{shortLong1: 0},
	{triplets1: 0},
	{average2: 0},
	{average3: 0},
	{average4: 0},
	{average5: 0},
	{average6: 0},
	{average7: 0},
	{average8: 0},
	{triplets2: 0},
	{triplets3: 0},
	{triplets4: 0},
	{triplets5: 0},
	{triplets6: 0},
	{triplets7: 0},
	{triplets8: 0},
	{shortLong2: 0},
	{shortLong3: 0},
	{shortLong4: 0},
	{shortLong5: 0},
	{shortLong6: 0},
	{shortLong7: 0},
	{shortLong8: 0},
	{StartCreating: 0},
	{Sprite: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{PedalPullGeneration: 0},
	{PedalPullred: 0},
	{ClapGeneration: 0},
	{clap: 0},
	{boomgeneration: 0},
	{boomgreen: 0},
	{bapgeneration: 0},
	{bapblue: 0},
	{Click: 0},
	{box10: 0},
	{box11: 0},
	{box12: 0},
	{box13: 0},
	{box14: 0},
	{box15: 0},
	{box16: 0},
	{box17: 0},
	{h5: 0},
	{h6: 0},
	{h7: 0},
	{h8: 0},
	{l5: 0},
	{l6: 0},
	{l7: 0},
	{l8: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{sheetMusicbg: 0},
	{trapMusicalNarration: 0},
	{illustrate: 0},
	{Sprite18: 0},
	{"2bg": 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{GoToNextUnit: 0},
	{review: 0},
	{Touch: 0},
	{Karaoke: 0},
	{視頻: 0},
	{HTML元素: 0},
	{empty2: 0},
	{empty1: 0},
	{empty3: 0},
	{Text6: 0},
	{Text7: 0},
	{Sprite10: 0},
	{視頻2: 0},
	{practice1oldSchool: 0},
	{practice2: 0},
	{practice3: 0},
	{practice1trap: 0},
	{I9: 0},
	{I10: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Text8: 0},
	{Text9: 0},
	{QAQ: 0},
	{Sprite24: 0},
	{PreviousPage: 0},
	{Sprite25: 0},
	{"3illustrate": 0},
	{Text10: 0},
	{Text11: 0},
	{字卡: 0},
	{卡拉ok: 0},
	{hind: 0},
	{move: 0},
	{testtry: 0},
	{點擊: 0},
	{level: 0},
	{over: 0},
	{text: 0},
	{T: 0},
	{level2: 0},
	{over2: 0},
	{lowhigh: 0}
];

self.InstanceType = {
	b1: class extends self.ISpriteInstance {},
	b2: class extends self.ISpriteInstance {},
	b3: class extends self.ISpriteInstance {},
	b4: class extends self.ISpriteInstance {},
	b5: class extends self.ISpriteInstance {},
	s1: class extends self.ISpriteInstance {},
	s2: class extends self.ISpriteInstance {},
	s3: class extends self.ISpriteInstance {},
	s4: class extends self.ISpriteInstance {},
	s5: class extends self.ISpriteInstance {},
	大: class extends self.ISpriteInstance {},
	大鼓: class extends self.ISpriteInstance {},
	大鼓2: class extends self.ISpriteInstance {},
	__InvalidName0__: class extends self.ISpriteInstance {},
	小: class extends self.ISpriteInstance {},
	小鼓: class extends self.ISpriteInstance {},
	小鼓2: class extends self.ISpriteInstance {},
	title: class extends self.ISpriteInstance {},
	start: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	starttext: class extends self.ITextInstance {},
	滑鼠: class extends self.IInstance {},
	_1map: class extends self.ISpriteInstance {},
	_2mapp: class extends self.ISpriteInstance {},
	_3map: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	_1text: class extends self.ITextInstance {},
	_1Understand: class extends self.ITextInstance {},
	narration: class extends self.ITextInstance {},
	oldSchool: class extends self.ISpriteInstance {},
	trap: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Spectrum: class extends self.ISpriteInstance {},
	boom: class extends self.ITextInstance {},
	bap: class extends self.ITextInstance {},
	map: class extends self.ISpriteInstance {},
	oldtrap: class extends self.ISpriteInstance {},
	next: class extends self.ISpriteInstance {},
	help: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	ok: class extends self.ISpriteInstance {},
	ill: class extends self.ISpriteInstance {},
	音頻: class extends self.IInstance {},
	SensorDetector: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	ChallengeSuccessOrFailure: class extends self.ISpriteInstance {},
	again: class extends self.ISpriteInstance {},
	clear: class extends self.ISpriteInstance {},
	back: class extends self.ISpriteInstance {},
	trapbg: class extends self.ISpriteInstance {},
	dialogBox: class extends self.ISpriteInstance {},
	PedalPull1: class extends self.ISpriteInstance {},
	bass: class extends self.ISpriteInstance {},
	Spectrum2: class extends self.ISpriteInstance {},
	Spectrum3: class extends self.ISpriteInstance {},
	PedalPull2: class extends self.ISpriteInstance {},
	bass2: class extends self.ISpriteInstance {},
	box: class extends self.ISpriteInstance {},
	box2: class extends self.ISpriteInstance {},
	box3: class extends self.ISpriteInstance {},
	box4: class extends self.ISpriteInstance {},
	box5: class extends self.ISpriteInstance {},
	box6: class extends self.ISpriteInstance {},
	box7: class extends self.ISpriteInstance {},
	box8: class extends self.ISpriteInstance {},
	h1: class extends self.ISpriteInstance {},
	h2: class extends self.ISpriteInstance {},
	h3: class extends self.ISpriteInstance {},
	h4: class extends self.ISpriteInstance {},
	l1: class extends self.ISpriteInstance {},
	l2: class extends self.ISpriteInstance {},
	l3: class extends self.ISpriteInstance {},
	l4: class extends self.ISpriteInstance {},
	averagecard: class extends self.ISpriteInstance {},
	shortLongcard: class extends self.ISpriteInstance {},
	tripletscard: class extends self.ISpriteInstance {},
	Text4: class extends self.ITextInstance {},
	wordCardBelow: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {},
	CharacterCardDescription: class extends self.ISpriteInstance {},
	backclick: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	QuizAndCreate: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	cube: class extends self.ISpriteInstance {},
	cube2: class extends self.ISpriteInstance {},
	cube3: class extends self.ISpriteInstance {},
	cube4: class extends self.ISpriteInstance {},
	cube5: class extends self.ISpriteInstance {},
	cube6: class extends self.ISpriteInstance {},
	cube7: class extends self.ISpriteInstance {},
	cube8: class extends self.ISpriteInstance {},
	average1: class extends self.ISpriteInstance {},
	shortLong1: class extends self.ISpriteInstance {},
	triplets1: class extends self.ISpriteInstance {},
	average2: class extends self.ISpriteInstance {},
	average3: class extends self.ISpriteInstance {},
	average4: class extends self.ISpriteInstance {},
	average5: class extends self.ISpriteInstance {},
	average6: class extends self.ISpriteInstance {},
	average7: class extends self.ISpriteInstance {},
	average8: class extends self.ISpriteInstance {},
	triplets2: class extends self.ISpriteInstance {},
	triplets3: class extends self.ISpriteInstance {},
	triplets4: class extends self.ISpriteInstance {},
	triplets5: class extends self.ISpriteInstance {},
	triplets6: class extends self.ISpriteInstance {},
	triplets7: class extends self.ISpriteInstance {},
	triplets8: class extends self.ISpriteInstance {},
	shortLong2: class extends self.ISpriteInstance {},
	shortLong3: class extends self.ISpriteInstance {},
	shortLong4: class extends self.ISpriteInstance {},
	shortLong5: class extends self.ISpriteInstance {},
	shortLong6: class extends self.ISpriteInstance {},
	shortLong7: class extends self.ISpriteInstance {},
	shortLong8: class extends self.ISpriteInstance {},
	StartCreating: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	PedalPullGeneration: class extends self.ISpriteInstance {},
	PedalPullred: class extends self.ISpriteInstance {},
	ClapGeneration: class extends self.ISpriteInstance {},
	clap: class extends self.ISpriteInstance {},
	boomgeneration: class extends self.ISpriteInstance {},
	boomgreen: class extends self.ISpriteInstance {},
	bapgeneration: class extends self.ISpriteInstance {},
	bapblue: class extends self.ISpriteInstance {},
	Click: class extends self.ISpriteInstance {},
	box10: class extends self.ISpriteInstance {},
	box11: class extends self.ISpriteInstance {},
	box12: class extends self.ISpriteInstance {},
	box13: class extends self.ISpriteInstance {},
	box14: class extends self.ISpriteInstance {},
	box15: class extends self.ISpriteInstance {},
	box16: class extends self.ISpriteInstance {},
	box17: class extends self.ISpriteInstance {},
	h5: class extends self.ISpriteInstance {},
	h6: class extends self.ISpriteInstance {},
	h7: class extends self.ISpriteInstance {},
	h8: class extends self.ISpriteInstance {},
	l5: class extends self.ISpriteInstance {},
	l6: class extends self.ISpriteInstance {},
	l7: class extends self.ISpriteInstance {},
	l8: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	sheetMusicbg: class extends self.ISpriteInstance {},
	trapMusicalNarration: class extends self.ISpriteInstance {},
	illustrate: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	_2bg: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	GoToNextUnit: class extends self.ISpriteInstance {},
	review: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Karaoke: class extends self.ISpriteInstance {},
	視頻: class extends self.IWorldInstance {},
	HTML元素: class extends self.IHTMLElementInstance {},
	empty2: class extends self.ISpriteInstance {},
	empty1: class extends self.ISpriteInstance {},
	empty3: class extends self.ISpriteInstance {},
	Text6: class extends self.ITextInstance {},
	Text7: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	視頻2: class extends self.IWorldInstance {},
	practice1oldSchool: class extends self.ISpriteInstance {},
	practice2: class extends self.ISpriteInstance {},
	practice3: class extends self.ISpriteInstance {},
	practice1trap: class extends self.ISpriteInstance {},
	I9: class extends self.ISpriteInstance {},
	I10: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Text8: class extends self.ITextInstance {},
	Text9: class extends self.ITextInstance {},
	QAQ: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	PreviousPage: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	_3illustrate: class extends self.ISpriteInstance {},
	Text10: class extends self.ITextInstance {},
	Text11: class extends self.ITextInstance {}
}